wis2box-api for wis2box-api-1.0b7
wmo-im/wis2box-api pull request #45
Opened 2024-01-16 12:55 UTC by maaikelimper

2024-01-22 02:11 UTC, tomkralidis requested changes
Some minor changes requests.  Overall comment to order imports as follows;

- standard library
- 3rd party packages
- local modules

```python
import os
import sys

import paho.mqtt
import requests

import local.foo_module
import local.z_module
```

2024-01-22 02:11 UTC, tomkralidis commented on docker_compose_test/tests/integration/test_wis2box.py
> +    assert message['channel'] == expected_message['channel']
```python
    for key in ['channel', 'filename', 'data', '_meta']:
        assert message[key] == expected_message[key]
```

2024-01-24 10:56 UTC, maaikelimper commented on docker_compose_test/tests/integration/test_wis2box.py
> +    assert message['channel'] == expected_message['channel']
ok

2024-01-24 10:57 UTC, maaikelimper commented on docker_compose_test/docker-compose.yml
> +      dockerfile: Dockerfile
nope, removed

2024-01-24 10:58 UTC, maaikelimper commented on docker/pygeoapi-config.yml
> +    manager:
I added a cronjob removing successful jobs after one hour

2024-02-27 08:07 UTC, merged